### PR TITLE
First draft of 'manual partitioning' guide

### PR DESCRIPTION
**Pull request by miabbott**
This adds the text and images for the 'Manual Partitioning' part of the Installation Guide.

### CODE REVIEW

**Comment by miabbott** [comment]
These changes are made on top of #10; I can rebase once that is merged or just move that commit over there, if that is easier.

**Comment by sanjabonic** [comment]
Rebase, please.

**Comment by sanjabonic** [comment]
There are some sizing issues which I'll fix after we merge all of this.

**Comment by sanjabonic** [comment]
Rebase, please.

There are some sizing issues which I'll fix when this is all merged, so no worries about that. Also, thanks for the PR - really nice!

**Comment by miabbott** [comment]
Had to force push my rebase, but should be good to go

**Pull request merged**
